apiVersion: v1
kind: Service
metadata:
  name: `(s-chop-suffix "-service" (file-name-base (or (buffer-file-name) (buffer-name))))`
  labels:
    app: `(s-chop-suffix "-service" (file-name-base (or (buffer-file-name) (buffer-name))))`
spec:
  type: ClusterIP
  ports:
    - port:
  selector:
    app: `(s-chop-suffix "-service" (file-name-base (or (buffer-file-name) (buffer-name))))`
$0
