kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: `(file-name-base (or (buffer-file-name) (buffer-name)))`
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:
$0
